---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    git_cloning: []
    git_device_cloning: []
  tasks:
    - name: Git | Converge | Include the ansible-git role
      ansible.builtin.include_role:
        name: ansible-git
