---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:12
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ../tests
