---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Git | Prepare | Install Python3 and sudo for Ansible module support
      ansible.builtin.raw: >
        apt-get update -qq &&
        apt-get install -y -qq python3 sudo
      changed_when: false
